baseURL = "https://reliability.re/"
languageCode = "en-us"
title = "Reliability Report 📰"
theme = "hyde"

[params]
  themeColor = "theme-base-08"
  description = "A collaborative curated content site about Reliability Engineering"

[Menus]
  main = [
    {Name = "Contributing", URL = "/contribute/"},
  ]

[deployment]
order = [".png$", ".jpg$", ".gif$", ".svg$"]

[[deployment.targets]]
name = "aws"
URL = "s3://reliability.re?region=eu-west-1"

#[[deployment.matchers]]
# Cache static assets for 20 years.
#pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
#cacheControl = "max-age=630720000, no-transform, public"
#gzip = true

#[[deployment.matchers]]
#pattern = "^.+\\.(html|xml|json)$"
#gzip = true
